"""
Store mappings and group of clinically relevant concepts.
"""

CONCEPT_HYDROCORTISONE = {
    # Found in emar (WARNING: only available for 2011-2013)
    "emar": [
        "Hydrocortisone Acetate Suppository",
        "Hydrocortisone Cream 0.5%",
        "Hydrocortisone Enema",
        "hydrocortisone study drug",
        "Hydrocortisone Cream 1%",
        "Hydrocortisone Oint 1%",
        "Hydrocortisone Na Succ.",
        "Hydrocortisone study med",
        "Hydrocortisone Acetate 10%  Foam",
        "hydrocorTISone Sod Succinate",
        "hydrocortisone-acetic acid",
        "hydrocorTISone Sod Succ (PF)",
        "Hydrocortisone Oint 2.5%",
        "Hydrocortisone ",
        "hydrocortisone Study drug",
        "Hydrocortisone (Rectal) 2.5% Cream",
        "Hydrocortisone Study Drug",
        "Hydrocortisone",
        "Hydrocortisone Study drug",
        "Hydrocortisone Study Drug ",
        "hydrocorTISone",
        "Hydrocortisone study drug",
        "Hydrocortisone/study med",
        "Hydrocortisone Cream 2.5%",
        "Hydrocortisone Oint 0.5%",
        "Hydrocortisone Val. Cream 0.2%",
    ],
    # Found in pharmacy:
    "pharmacy": [
        "Hydrocortisone Acetate Ointment 1%",
        "Hydrocortisone Cream 1%",
        "Hydrocortisone Na Succinate",
        "hydrocorTISone",
        "Hydrocortisone Val. Cream 0.2%",
        "lidocaine 3% - hydrocortisone 0.5%",
        "hydrocorTISone Sod Succinate",
        "Hydrocortisone Oint 0.5%",
        "hydrocortisone-iodoquinl-aloe2",
        "Hydrocortisone",
        "Hydrocortisone Cream 2.5%",
        "Hydrocortisone Enema",
        "hydrocortisone ",
        "hydrocortisone-pramoxine",
        "Hydrocortisone Acetate Suppository",
        "Hydrocortisone Oint 2.5%",
        "Hydrocortisone Cream 0.5%",
        "Hydrocortisone/",
        "Hydrocortisone (Rectal) 2.5% Cream",
        "lidocaine-hydrocortisone ac",
        "Cortisone (hydrocortisone)",
        "Hydrocortisone ",
        "hydrocortisone-acetic acid",
        "Hydrocortisone 100mg",
        "hydrocorTISone Sod Succ (PF)",
        "Lidocaine-Hydrocortisone Ac",
        "Hydrocortisone Lotion 1%",
        "Hydrocortisone Acetate 10%  Foam",
        "Hydrocortisone Oint 1%",
        "hydrocortisone",
        "Hydrocortisone Acetate",
        "Hydrocortisone Na Succ.",
        "Hydrocortisone Na Succ",
        "Hydrocortisone Cream",
    ],
}
